# Generated by Django 4.2.23 on 2025-06-13 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_eventavailability_date_alter_timeslot_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventavailability',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.timeslot'),
        ),
    ]
