# Generated by Django 4.2.23 on 2025-06-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_alter_eventavailability_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to='booking_app.eventavailability'),
        ),
    ]
